# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14b6dcb1ae38a84e89a71beb02bf9fa0904f858ea9c9c6ce6b50d43eeedccb6db7d2839842b36e2f0e83a88ab58505b8b7dab5ce66d65a4b55fce32f6d3c90c4

test:
  secret_key_base: 877b4fa3223083c9d7a68971e982cb910ccf1260ee5c6a63a637df52b9764636c57b3837615be10b9ae0335b90b8cd0cc0d7d3fca39a0724cdf0883bfeba85ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
